### ISSUE TITLE
Cobweb crash when using 1.21.1

### ISSUE THREAD

**Issue by Disketaa** [Crystal-Nest/cobweb#5]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

![image](https://github.com/user-attachments/assets/34f6b015-cfb4-486a-b464-99a25c346633)
![image](https://github.com/user-attachments/assets/435320b1-cd0c-4298-bd2a-e3e0cd0a6f69)

### Expected behavior

Launch correctly

### Minecraft version

1.21.1

### Mod loader version

0.16.5

### Mod version

1.1.2

### Other mods

None

**Comment by Crystal-Spider** [comment]
Fixed with Cobweb v1.1.3 and Soul Fire'd v5.0.4.
